fixed, now building automatically

diff --git a/modular-tools b/modular-tools
--- a/modular-tools
+++ b/modular-tools
@@ -63,6 +63,25 @@ sshd_fix()
 	cp sources/meta-bsp-me9/tools/sshd_config sources/poky/meta/recipes-connectivity/openssh/openssh/sshd_config
 }
 
+fix_path()
+{
+
+# Define the path to the original bblayers.conf file
+BBLAYERS_CONF_ORG="build/conf/bblayers.conf.org"
+BBLAYERS_CONF_ORG="build/conf/bblayers.conf"
+# Check if the original bblayers.conf file exists
+if [ ! -f "$BBLAYERS_CONF_ORG" ]; then
+    echo "Error: bblayers.conf.org not found at $BBLAYERS_CONF_ORG"
+    exit 1
+fi
+
+# Update the BSPDIR variable using sed
+sed -i 's|BSPDIR := "\${@os.path.abspath(os.path.dirname(d.getVar('"'"'FILE'"'"', True)) + '/../..')}"|BSPDIR := "\${@os.path.abspath(os.path.dirname(d.getVar('"'"'FILE'"'"', True)) + '/../')}"|' "$BBLAYERS_CONF_ORG"
+
+sed -i 's|BSPDIR := "\${@os.path.abspath(os.path.dirname(d.getVar('"'"'FILE'"'"', True)) + '/../..')}"|BSPDIR := "\${@os.path.abspath(os.path.dirname(d.getVar('"'"'FILE'"'"', True)) + '/../')}"|' "$BBLAYERS_CONF"
+echo "BSPDIR has been updated in bblayers.conf.org"
+	
+}
 add_new_layer() {
 	cp sources/meta-bsp-kratos/bblayers.confpre conf/bblayers.conf.org
 }
@@ -73,6 +92,7 @@ build_image()
 	machine_type
 	sanity_fix
 	bitbake -k core-image-base
+	#fix_path
 }
 
 build_sdk()
